"""moon_feedback table

Revision ID: 26b87717db69
Revises: 62fd79bb9256
Create Date: 2026-05-27 17:06:24.121913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b87717db69'
down_revision: Union[str, Sequence[str], None] = '62fd79bb9256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.String(length=4), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('profile_snapshot', sa.JSON(), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_moon_feedback_created_at'), 'moon_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_moon_feedback_user_id'), 'moon_feedback', ['user_id'], unique=False)
    # NOTE: ingredient_category_compatibility is seeded outside the ORM (no model);
    # autogenerate keeps proposing its drop. Do NOT drop it. Removed.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_moon_feedback_user_id'), table_name='moon_feedback')
    op.drop_index(op.f('ix_moon_feedback_created_at'), table_name='moon_feedback')
    op.drop_table('moon_feedback')
