"""add normalized tables for ingredients claims images compositions validation

Revision ID: 5d765dc62209
Revises: df5bfad603d9
Create Date: 2026-03-14 01:04:18.568936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d765dc62209'
down_revision: Union[str, Sequence[str], None] = 'df5bfad603d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('inci_name', sa.Text(), nullable=True),
    sa.Column('cas_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('safety_rating', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('claim_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('product_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'claim_id')
    )
    op.create_index(op.f('ix_product_claims_claim_id'), 'product_claims', ['claim_id'], unique=False)
    op.create_index(op.f('ix_product_claims_product_id'), 'product_claims', ['product_id'], unique=False)
    op.create_table('product_compositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('section_label', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_selector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_compositions_product_id'), 'product_compositions', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'ingredient_id')
    )
    op.create_index(op.f('ix_product_ingredients_ingredient_id'), 'product_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_product_ingredients_product_id'), 'product_ingredients', ['product_id'], unique=False)
    op.create_table('validation_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('pass_1_value', sa.Text(), nullable=True),
    sa.Column('pass_2_value', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_comparisons_product_id'), 'validation_comparisons', ['product_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['validation_comparisons.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_product_id'), 'review_queue', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_product_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_validation_comparisons_product_id'), table_name='validation_comparisons')
    op.drop_table('validation_comparisons')
    op.drop_index(op.f('ix_product_ingredients_product_id'), table_name='product_ingredients')
    op.drop_index(op.f('ix_product_ingredients_ingredient_id'), table_name='product_ingredients')
    op.drop_table('product_ingredients')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_compositions_product_id'), table_name='product_compositions')
    op.drop_table('product_compositions')
    op.drop_index(op.f('ix_product_claims_product_id'), table_name='product_claims')
    op.drop_index(op.f('ix_product_claims_claim_id'), table_name='product_claims')
    op.drop_table('product_claims')
    op.drop_table('ingredient_aliases')
    op.drop_table('claim_aliases')
    op.drop_table('ingredients')
    op.drop_table('claims')
    # ### end Alembic commands ###
