"""hair_profiles table for Moon

Revision ID: 62fd79bb9256
Revises: m00n1f0und4t10n
Create Date: 2026-05-27 04:26:05.155642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fd79bb9256'
down_revision: Union[str, Sequence[str], None] = 'm00n1f0und4t10n'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('curl_type', sa.String(length=20), nullable=True),
    sa.Column('curl_subtype', sa.String(length=6), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('volume', sa.String(length=10), nullable=True),
    sa.Column('thickness', sa.String(length=10), nullable=True),
    sa.Column('length', sa.String(length=12), nullable=True),
    sa.Column('scalp_oiliness', sa.String(length=10), nullable=True),
    sa.Column('dryness_damage', sa.String(length=10), nullable=True),
    sa.Column('chemical_treatments', sa.JSON(), nullable=True),
    sa.Column('heat_usage', sa.String(length=12), nullable=True),
    sa.Column('extensions', sa.String(length=10), nullable=True),
    sa.Column('wash_frequency', sa.String(length=20), nullable=True),
    sa.Column('sun_exposure', sa.String(length=10), nullable=True),
    sa.Column('water_exposure', sa.String(length=12), nullable=True),
    sa.Column('scalp_issues', sa.Boolean(), nullable=True),
    sa.Column('conditionals', sa.JSON(), nullable=True),
    sa.Column('raw_answers', sa.JSON(), nullable=True),
    sa.Column('derived_hair_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_hair_profiles_user_id'), 'hair_profiles', ['user_id'], unique=True)
    # NOTE: autogenerate also proposed dropping `ingredient_category_compatibility`
    # because that table is created/seeded outside the ORM (no model). It is the
    # backbone of Moon's scoring — do NOT drop it. Removed from this migration.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_hair_profiles_user_id'), table_name='hair_profiles')
    op.drop_table('hair_profiles')
