"""initial schema

Revision ID: 6c9163e9ad24
Revises: 
Create Date: 2026-02-24 15:35:19.568668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9163e9ad24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_coverage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_slug', sa.String(length=255), nullable=False),
    sa.Column('discovered_total', sa.Integer(), nullable=False),
    sa.Column('hair_total', sa.Integer(), nullable=False),
    sa.Column('kits_total', sa.Integer(), nullable=False),
    sa.Column('non_hair_total', sa.Integer(), nullable=False),
    sa.Column('extracted_total', sa.Integer(), nullable=False),
    sa.Column('verified_inci_total', sa.Integer(), nullable=False),
    sa.Column('verified_inci_rate', sa.Float(), nullable=False),
    sa.Column('catalog_only_total', sa.Integer(), nullable=False),
    sa.Column('quarantined_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('blueprint_version', sa.Integer(), nullable=False),
    sa.Column('coverage_report', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_slug')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brand_slug', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('product_url', sa.String(length=2000), nullable=False),
    sa.Column('image_url_main', sa.String(length=2000), nullable=True),
    sa.Column('image_urls_gallery', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('product_type_raw', sa.String(length=255), nullable=True),
    sa.Column('product_type_normalized', sa.String(length=100), nullable=True),
    sa.Column('gender_target', sa.String(length=20), nullable=False),
    sa.Column('hair_relevance_reason', sa.Text(), nullable=True),
    sa.Column('inci_ingredients', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_instructions', sa.Text(), nullable=True),
    sa.Column('benefits_claims', sa.JSON(), nullable=True),
    sa.Column('size_volume', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('line_collection', sa.String(length=255), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url')
    )
    op.create_index(op.f('ix_products_brand_slug'), 'products', ['brand_slug'], unique=False)
    op.create_table('product_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('evidence_locator', sa.String(length=500), nullable=True),
    sa.Column('raw_source_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarantine_details',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('rejection_code', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarantine_details')
    op.drop_table('product_evidence')
    op.drop_index(op.f('ix_products_brand_slug'), table_name='products')
    op.drop_table('products')
    op.drop_table('brand_coverage')
    # ### end Alembic commands ###
