"""add ops panel columns and tables

Revision ID: 760c4a916b6b
Revises: 5d765dc62209
Create Date: 2026-03-18 11:45:30.612395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760c4a916b6b'
down_revision: Union[str, Sequence[str], None] = '5d765dc62209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('revision_history',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('change_source', sa.String(length=20), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_revision_history_entity_id'), 'revision_history', ['entity_id'], unique=False)
    op.add_column('products', sa.Column('status_operacional', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('status_editorial', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('status_publicacao', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('assigned_to', sa.String(length=36), nullable=True))
    op.add_column('products', sa.Column('confidence_factors', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('interpretation_data', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('application_data', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('decision_data', sa.JSON(), nullable=True))
    # FK constraint for assigned_to -> users.user_id
    # SQLite doesn't support ALTER for constraints, so use batch mode
    with op.batch_alter_table('products') as batch_op:
        batch_op.create_foreign_key('fk_products_assigned_to', 'users', ['assigned_to'], ['user_id'])
    # ### end Alembic commands ###

    # Backfill status columns from verification_status
    op.execute("""
        UPDATE products SET
            status_operacional = CASE
                WHEN verification_status = 'verified_inci' THEN 'validado'
                WHEN verification_status = 'catalog_only' THEN 'extraido'
                WHEN verification_status = 'quarantined' THEN 'extraido'
                ELSE 'bruto'
            END,
            status_editorial = CASE
                WHEN verification_status = 'verified_inci' THEN 'aprovado'
                WHEN verification_status = 'catalog_only' THEN 'pendente'
                WHEN verification_status = 'quarantined' THEN 'pendente'
                ELSE 'pendente'
            END,
            status_publicacao = CASE
                WHEN verification_status = 'verified_inci' THEN 'publicado'
                ELSE 'rascunho'
            END
        WHERE status_operacional IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_products_assigned_to', type_='foreignkey')
    op.drop_column('products', 'decision_data')
    op.drop_column('products', 'application_data')
    op.drop_column('products', 'interpretation_data')
    op.drop_column('products', 'confidence_factors')
    op.drop_column('products', 'assigned_to')
    op.drop_column('products', 'status_publicacao')
    op.drop_column('products', 'status_editorial')
    op.drop_column('products', 'status_operacional')
    op.drop_index(op.f('ix_revision_history_entity_id'), table_name='revision_history')
    op.drop_table('revision_history')
    op.drop_table('users')
    # ### end Alembic commands ###
