"""moon conversations and messages

Revision ID: a88cdb85fe82
Revises: ce192517ade2
Create Date: 2026-05-29 04:11:42.456841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88cdb85fe82'
down_revision: Union[str, Sequence[str], None] = 'ce192517ade2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon_conversations',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_moon_conversations_created_at'), 'moon_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_moon_conversations_last_message_at'), 'moon_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_moon_conversations_user_id'), 'moon_conversations', ['user_id'], unique=False)
    op.create_table('moon_messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('kb_sources', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['moon_conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_moon_messages_conversation_id'), 'moon_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_moon_messages_created_at'), 'moon_messages', ['created_at'], unique=False)
    # NOTE: ingredient_category_compatibility is seeded outside the ORM; autogen
    # keeps proposing its drop. Do NOT drop it.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_moon_messages_created_at'), table_name='moon_messages')
    op.drop_index(op.f('ix_moon_messages_conversation_id'), table_name='moon_messages')
    op.drop_table('moon_messages')
    op.drop_index(op.f('ix_moon_conversations_user_id'), table_name='moon_conversations')
    op.drop_index(op.f('ix_moon_conversations_last_message_at'), table_name='moon_conversations')
    op.drop_index(op.f('ix_moon_conversations_created_at'), table_name='moon_conversations')
    op.drop_table('moon_conversations')
    # ### end Alembic commands ###
