"""add product_labels column

Revision ID: bf5a62d6a28b
Revises: 6c9163e9ad24
Create Date: 2026-02-26 10:39:01.910392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5a62d6a28b'
down_revision: Union[str, Sequence[str], None] = '6c9163e9ad24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_labels')
    # ### end Alembic commands ###
