"""knowledge_chunks table

Revision ID: ce192517ade2
Revises: 26b87717db69
Create Date: 2026-05-29 01:57:00.678848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce192517ade2'
down_revision: Union[str, Sequence[str], None] = '26b87717db69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    # NOTE: ingredient_category_compatibility is seeded outside the ORM; autogen
    # keeps proposing its drop. Do NOT drop it.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('knowledge_chunks')
