"""add is_kit column to products

Revision ID: df5bfad603d9
Revises: d4b8e2f3a567
Create Date: 2026-03-06 17:02:59.915859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5bfad603d9'
down_revision: Union[str, Sequence[str], None] = 'd4b8e2f3a567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_kit', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_products_is_kit'), 'products', ['is_kit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_kit'), table_name='products')
    op.drop_column('products', 'is_kit')
    # ### end Alembic commands ###
